# Generated by Django 6.0.4 on 2026-04-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuario_emisor_id', models.IntegerField()),
                ('grupo_id', models.IntegerField(blank=True, null=True)),
                ('canal_id', models.IntegerField(blank=True, null=True)),
                ('usuario_receptor_id', models.IntegerField(blank=True, null=True)),
                ('tipo_destino', models.CharField(choices=[('grupo', 'Grupo'), ('canal', 'Canal'), ('privado', 'Privado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_destinatario_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído')], max_length=10)),
                ('fecha_estado', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='chat_messages.mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tipo', models.CharField(max_length=50)),
                ('tamaño', models.IntegerField()),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='chat_messages.mensaje')),
            ],
        ),
    ]
